Update Pipeline failure logging
This commit changes the default behavior as follow;

- Do not truncate the log.
- Do not suppress repeated failures.

Follow-up: Introduce a switching mechanism
(perhaps environment variable) to switch back to the original behavior.

Example

<details><summary>Code></summary>

```
def nope(i: int):
    if i > 0:
        return nope(i - 1)
    return 1 / 0

def main():
    pipeline = (
        PipelineBuilder()
        .add_source(range(30))
        .pipe(nope)
        .add_sink(3)
        .build(num_threads=1)
    )

    with pipeline.auto_stop():
        list(pipeline)
```

</details>

<details><summary>Before</summary>

```
ERROR:spdl.pipeline._utils:Task [0:1:nope:1]: ZeroDivisionError: division by zero (/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py:13:nope)
WARNING:spdl.pipeline._utils:Errors are repeated at /data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py:13:nope, holding on logging.
```

</details>

<details><summary>After</summary>

```
ERROR:spdl.pipeline._utils:Task [0:1:nope:1] failed.
Traceback (most recent call last):
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/spdl/pipeline/_utils.py", line 59, in _log_exception
    task.result()
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/spdl/pipeline/_components/_pipe.py", line 60, in _wrap_afunc
    result = await coro
             ^^^^^^^^^^
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/spdl/pipeline/_convert.py", line 62, in afunc
    return await loop.run_in_executor(executor, func, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py", line 13, in nope
    return 1 / 0
           ~~^~~
ZeroDivisionError: division by zero

...

ERROR:spdl.pipeline._utils:Task [0:1:nope:30] failed.
Traceback (most recent call last):
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/spdl/pipeline/_utils.py", line 59, in _log_exception
    task.result()
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/spdl/pipeline/_components/_pipe.py", line 60, in _wrap_afunc
    result = await coro
             ^^^^^^^^^^
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/spdl/pipeline/_convert.py", line 62, in afunc
    return await loop.run_in_executor(executor, func, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py", line 12, in nope
    return nope(i - 1)
           ^^^^^^^^^^^
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py", line 12, in nope
    return nope(i - 1)
           ^^^^^^^^^^^
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py", line 12, in nope
    return nope(i - 1)
           ^^^^^^^^^^^
  [Previous line repeated 26 more times]
  File "/data/users/moto/fbsource/buck-out/v2/gen/fbcode/7893ad05317a11d1/scripts/moto/__debug_logging__/debug_logging#link-tree/scripts/moto/debug_logging.py", line 13, in nope
    return 1 / 0
           ~~^~~
ZeroDivisionError: division by zero
```

</details>